//
//  Constants.m
//  TorresDeOeste
//
//  Created by Evelb on 8/10/16.
//  Copyright © 2016 Evelb. All rights reserved.
//

#import "Constants.h"

@implementation Constants


NSString *SETTINGS_WAS_STARTED_APP_BEFORE = @"SETTINGS_WAS_STARTED_APP_BEFORE";
NSString *SETTINGS_kDATE_LAST_UPDATE_PARAMETERS = @"SETTINGS_kDATE_LAST_UPDATE_PARAMETERS";
NSString *SETTINGS_kDATE_LAST_UPDATE_MENU = @"SETTINGS_kDATE_LAST_UPDATE_MENU";
NSString *SETTINGS_kDATE_LAST_UPDATE_GUIA = @"SETTINGS_kDATE_LAST_UPDATE_GUIA";
NSString *SETTINGS_kDATE_LAST_UPDATE_GUIA_DETALLE = @"SETTINGS_kDATE_LAST_UPDATE_GUIA_DETALLE";
NSString *SETTINGS_kDATE_LAST_UPDATE_GUIA_DETALLE_IMAGEN = @"SETTINGS_kDATE_LAST_UPDATE_GUIA_DETALLE_IMAGEN";
NSString *SETTINGS_kDATE_LAST_UPDATE_GUIA_SABER_MAS = @"SETTINGS_kDATE_LAST_UPDATE_GUIA_SABER_MAS";
NSString *SETTINGS_kDATE_LAST_UPDATE_GUIA_SABER_MAS_DETALLE = @"SETTINGS_kDATE_LAST_UPDATE_GUIASABER_MAS_DETALLE";
NSString *SETTINGS_kDATE_LAST_UPDATE_GUIA_SABER_MAS_DETALLE_IMAGEN = @"SETTINGS_kDATE_LAST_UPDATE_GUIA_SABER_MAS_DETALLE_IMAGEN";

NSString *SETTINGS_kDATE_LAST_UPDATE_POI = @"SETTINGS_kDATE_LAST_UPDATE_POI";

NSString *SETTINGS_kDATE_LAST_UPDATE_IDIOMA = @"SETTINGS_kDATE_LAST_UPDATE_IDIOMA";

NSString *SETTINGS_IDIOMA = @"SETTINGS_IDIOMA";


NSString *k_URL_UPDATE_SERVICE = @"URL_SERVICIO_ACTUALIZACION";

///URL


NSString *const kURL_GET_PARAMETROS = @"WSParametros/getParametros";
NSString *const kURL_GET_MENU = @"WSMenu/getMenu";

NSString *const kURL_GET_IDIOMA = @"WSIdioma/getIdioma";
NSString *const kURL_GET_NOVEDADES = @"WSNovedades/getNovedades";
NSString *const kURL_GET_POIS = @"WSPOIS/getPOIs";

NSString *const kURL_GET_GUIA=@"WSGuias/getGuias";
NSString *const kURL_GET_GUIA_DETALLE = @"WSGuias/getGuiasDetalle";

NSString *const kURL_GET_GUIA_SABER_MAS = @"WSGuias/getGuiasSaberMas";

NSString *const kURL_GET_GUIA_SABER_MAS_DETALLE = @"WSGuias/getGuiasSaberMasDetalle";
NSString *const kURL_GET_IMAGE = @"WSImages/getImage";

//NSNotifications

NSString * const kNOTIFICATION_GO_TO = @"kNOTIFICATION_GO_TO";

NSString * const kNOTIFICATION_UPDATE_MENU = @"kNOTIFICATION_UPDATE_MENU";

//splash
double const k_NUMBER_DOWNLOADS_CHARGE = 5.0;

// SEGUES

NSString * const kSEGUE_HOME =  @"kSEGUE_HOME";
NSString * const kSEGUE_POI =  @"kSEGUE_POI";
NSString * const kSEGUE_LIST_POI = @"kSEGUE_LIST_POI";




@end
