platform :ios, '8.0'

def shared_pods
	pod 'AFNetworking', '~> 2.6'
	pod 'SDWebImage', '~>3.8'
	pod 'MMDrawerController', '~> 0.5.7'
    
end
target 'Torres Oeste' do
    shared_pods
end

target 'Baronha' do
    shared_pods
end

target 'Borneiro' do
    shared_pods
end
